[package]
authors = ["Gaute Hope <gaute.hope@met.no>"]
name = "landmaskpy"
version = "0.1.0"
edition = "2018"

[dependencies]
landmask = { version = "0.1.0", path = "../" }
pyo3 = { version = "*", features = ["extension-module"] }
numpy = "*"

[lib]
name = "landmask"
crate-type = ["cdylib"]
